[package]
name = "valute-evaluater-90"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
quick-xml = { version = "0.28", features = ["serialize"] }
reqwest = { version = "0.11", features = ["blocking"] }
serde = { version = "1.0", features = ["derive"] }
